apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-node-port
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.nodePort }}
  selector:
    app: 