grafana:
  ingress:
    host: grafana.soundstream.dev
    tlsSecretName: grafana-tls
    service:  prometheus-grafana
certManagerIssuer: 'letsencrypt'
kube-prometheus-stack:
  crds:
    enabled: false
  prometheus:
    prometheusSpec:
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
        fsGroup: 0
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: synology-iscsi-storage
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 5Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: 
        cert-manager.io/cluster-issuer: 'letsencrypt'
      hosts: 
        - prometheus.soundstream.dev
      paths:
        - '/'
      tls:
        - secretName: prometheus-soundstream-dev-tls
          hosts:
            - prometheus.soundstream.dev