apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
spec:
    acme:
        email: andreas.sundstrom+cert@hotmail.com
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: letencrypt-account-key
        solvers:
        - dns01:
            cloudflare:
                apiTokenSecretRef:
                    name: cloudflare-api-token-secret
                    key: api-token