apiVersion: v1
kind: Service
metadata:
    name: keycloak-postgres-db
spec:
    selector:
        app: {{ .Values.database.appName }}
    ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432