apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.database.serviceName }}
spec:
    selector:
        app: {{ .Values.database.appName }}
    ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432