# The port to expose on the cluster
ingress-nginx:
  controller:
    extraArgs:
      default-ssl-certificate: "default/my-cert"
    service:
      type: "NodePort"
      external:
        enabled: true
      nodePorts:
        https: 30840