global:
  domain: argocd.soundstream.dev

argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      extraTls:
        - hosts:
          - argocd.soundstream.dev
          secretName: argocd-server-tls
    certificate:
      enabled: true
      issuer:
        kind: 'ClusterIssuer'
        name: 'letsencrypt'